// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twfqgsicgntlukuciivo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZnFnc2ljZ250bHVrdWNpaXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MTcyNDIsImV4cCI6MjA1NjI5MzI0Mn0.NUwex35KLh1eqmJJzOdtKkw5yT6zMQsuY2v7g2E688c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);